server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monkey?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 10000
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.jiea.monkey.domain

