server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monkey?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 10000
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 6000
      jedis:
        pool:
          max-active: 100
          max-idle: 8
          max-wait: -1
          min-idle: 1
  thymeleaf:
    cache: false
    mode: HTML5

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.jiea.monkey.domain

